openapi: 3.0.0
paths:
  /users:
    get:
      operationId: getUserList
      summary: ''
      parameters: []
      responses:
        '200':
          description: ユーザー一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPresenter'
      tags: &ref_0
        - user
      security: &ref_2
        - &ref_1
          bearer: []
  /users/profile:
    get:
      operationId: getProfile
      summary: ''
      parameters: []
      responses:
        '200':
          description: プロフィール情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags: *ref_0
      security:
        - *ref_1
        - bearer: []
  /users/{id}:
    patch:
      operationId: updateUser
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          description: userId
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ユーザーの情報更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags: *ref_0
      security: *ref_2
    delete:
      operationId: UserController_delete
      parameters:
        - name: id
          required: true
          in: path
          description: userId
          schema:
            type: string
      responses:
        '204':
          description: ユーザー削除
      tags: *ref_0
      security: *ref_2
  /users/check:
    post:
      operationId: checkUser
      summary: ''
      parameters: []
      responses:
        '200':
          description: ユーザー情報のチェック
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags: *ref_0
      security: *ref_2
  /recipes:
    get:
      operationId: getRecipe
      summary: ''
      parameters: []
      responses:
        '200':
          description: レシピ一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipePresenter'
      tags: &ref_3
        - recipes
      security: &ref_4
        - bearer: []
    post:
      operationId: bulkInsertRecipes
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateRecipeDto'
      responses:
        '201':
          description: レシピ一括登録
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_3
      security: *ref_4
  /recipes/favorite:
    get:
      operationId: getRecipeByFavorite
      summary: ''
      parameters: []
      responses:
        '200':
          description: お気に入りレシピ一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_3
      security: *ref_4
  /recipes/{id}:
    get:
      operationId: getRecipe
      summary: ''
      parameters: []
      responses:
        '200':
          description: レシピ詳細取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_3
      security: *ref_4
    patch:
      operationId: updateRecipe
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRecipeDto'
      responses:
        '200':
          description: レシピ更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_3
      security: *ref_4
  /recipes/meta-data:
    get:
      operationId: getRecipeMetaData
      summary: ''
      parameters:
        - name: recipeIds
          required: true
          in: query
          description: レシピID
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: レシピメタデータ取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_3
      security: *ref_4
  /recipe-books/{id}:
    put:
      operationId: updateRecipeBook
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRecipeBookDto'
      responses:
        '200':
          description: 料理本更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags:
        - recipe-books
      security:
        - bearer: []
  /invitations/invitation:
    post:
      operationId: invitationSpace
      summary: ''
      parameters: []
      responses:
        '200':
          description: スペース招待
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationPresenter'
      tags: &ref_5
        - invitations
      security: &ref_6
        - bearer: []
  /invitations:
    put:
      operationId: validateInvitation
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateInvitationDto'
      responses:
        '200':
          description: スペース参加の検証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationPresenter'
      tags: *ref_5
      security: *ref_6
  /menus:
    get:
      operationId: getMenu
      summary: ''
      parameters: []
      responses:
        '200':
          description: 献立ー一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuPresenter'
      tags: &ref_7
        - menus
      security: &ref_8
        - bearer: []
    post:
      operationId: createMenu
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMenuDto'
      responses:
        '200':
          description: 献立の作成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_7
      security: *ref_8
  /menus/pending:
    get:
      operationId: getPendingMenu
      summary: ''
      parameters: []
      responses:
        '200':
          description: 提案メニュー一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_7
      security: *ref_8
  /menus/{id}:
    put:
      operationId: updateMenu
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMenuDto'
      responses:
        '200':
          description: 献立の更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_7
      security: *ref_8
    delete:
      operationId: deleteMenu
      summary: ''
      parameters: []
      responses:
        '200':
          description: 献立の削除
      tags: *ref_7
      security: *ref_8
  /spaces:
    post:
      operationId: createSpace
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSpaceDto'
      responses:
        '201':
          description: スペースと料理本を作成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpacePresenter'
      tags:
        - spaces
      security:
        - bearer: []
info:
  title: reciperu api app
  description: API documents
  version: '1.0'
  contact: {}
tags:
  - name: '1.0'
    description: ''
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    UserPresenter:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        activeStatus:
          type: string
          enum:
            - ONBOARDING
            - JOINED_SPACE
            - NOT_JOINED_SPACE
      required:
        - id
        - name
        - imageUrl
        - activeStatus
    UpdateUserDto:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        activeStatus:
          type: string
          enum:
            - ONBOARDING
            - JOINED_SPACE
            - NOT_JOINED_SPACE
      required:
        - name
        - imageUrl
        - activeStatus
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
      required:
        - id
        - name
        - imageUrl
    RecipePresenter:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
        appName:
          type: string
        faviconUrl:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - id
        - title
        - thumbnailUrl
        - imageUrls
        - memo
        - appName
        - faviconUrl
        - user
    CreateRecipeDto:
      type: object
      properties:
        title:
          type: string
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
      required:
        - title
        - thumbnailUrl
        - imageUrls
        - memo
    UpdateRecipeDto:
      type: object
      properties:
        title:
          type: string
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
      required:
        - title
        - thumbnailUrl
        - imageUrls
        - memo
    UpdateRecipeBookDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    InvitationPresenter:
      type: object
      properties:
        id:
          type: string
        token:
          type: string
        spaceId:
          type: string
      required:
        - id
        - token
        - spaceId
    ValidateInvitationDto:
      type: object
      properties:
        token:
          type: string
        spaceId:
          type: string
      required:
        - token
        - spaceId
    MenuPresenter:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
        user:
          $ref: '#/components/schemas/User'
        createdAt:
          format: date-time
          type: string
      required:
        - id
        - title
        - thumbnailUrl
        - imageUrls
        - memo
        - user
        - createdAt
    CreateMenuDto:
      type: object
      properties:
        recipeId:
          type: number
        scheduledAt:
          format: date-time
          type: string
      required:
        - recipeId
        - scheduledAt
    UpdateMenuDto:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    CreateSpaceDto:
      type: object
      properties:
        recipeBookName:
          type: string
      required:
        - recipeBookName
    RecipeBook:
      type: object
      properties: {}
    SpacePresenter:
      type: object
      properties:
        id:
          type: string
        recipeBook:
          $ref: '#/components/schemas/RecipeBook'
        users:
          type: array
          items:
            type: string
      required:
        - id
        - recipeBook
        - users
