openapi: 3.0.0
paths:
  /users:
    post:
      operationId: createUser
      summary: ''
      parameters: []
      responses:
        '201':
          description: The user has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntity'
      tags:
        - user
  /spaces:
    post:
      operationId: SpaceController_create
      parameters:
        - name: userUuid
          required: true
          in: query
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSpaceDto'
      responses:
        '201':
          description: The space has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
      tags: &ref_0
        - space
  /spaces/{uuid}:
    get:
      operationId: SpaceController_show
      parameters:
        - name: uuid
          required: true
          in: path
          description: space uuid
          schema:
            type: string
      responses:
        '200':
          description: The spaces has been successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
      tags: *ref_0
    patch:
      operationId: SpaceController_update
      parameters:
        - name: uuid
          required: true
          in: path
          description: space uuid
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSpaceDto'
      responses:
        '200':
          description: The space has been successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
      tags: *ref_0
info:
  title: reciperu api app
  description: API documents
  version: '1.0'
  contact: {}
tags:
  - name: '1.0'
    description: ''
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    UserEntity:
      type: object
      properties:
        id:
          type: number
        uuid:
          type: string
        name:
          type: string
        isOwner:
          type: boolean
        imageUrl:
          type: string
        uid:
          type: string
      required:
        - id
        - uuid
        - name
        - isOwner
        - imageUrl
        - uid
    UpsertSpaceDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Space:
      type: object
      properties:
        id:
          type: number
        uuid:
          type: string
        name:
          type: string
        createdAt:
          format: date-time
          type: string
      required:
        - id
        - uuid
        - name
        - createdAt
