openapi: 3.0.0
paths:
  /users/profile:
    get:
      operationId: getProfile
      summary: ''
      parameters: []
      responses:
        '200':
          description: プロフィール情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags: &ref_0
        - user
      security: &ref_1
        - bearer: []
  /users/{id}:
    patch:
      operationId: updateUser
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          description: userId
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ユーザーの情報更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags: *ref_0
      security: *ref_1
    delete:
      operationId: UserController_delete
      parameters:
        - name: id
          required: true
          in: path
          description: userId
          schema:
            type: string
      responses:
        '204':
          description: ユーザー削除
      tags: *ref_0
      security: *ref_1
  /recipes:
    get:
      operationId: getRecipe
      summary: ''
      parameters:
        - name: cursor
          required: false
          in: query
          description: カーソル
          schema:
            type: string
      responses:
        '200':
          description: レシピ一覧取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRecipePresenter'
      tags: &ref_2
        - recipes
      security: &ref_3
        - bearer: []
    post:
      operationId: createRecipe
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecipeDto'
      responses:
        '201':
          description: レシピ登録
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_2
      security: *ref_3
  /recipes/favorite:
    get:
      operationId: getRecipeByFavorite
      summary: ''
      parameters: []
      responses:
        '200':
          description: お気に入りレシピ一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_2
      security: *ref_3
  /recipes/{id}:
    get:
      operationId: getRecipe
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: レシピ詳細取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_2
      security: *ref_3
    put:
      operationId: updateRecipe
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRecipeDto'
      responses:
        '200':
          description: レシピ更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_2
      security: *ref_3
  /recipes/meta-data:
    get:
      operationId: getRecipeMetaData
      summary: ''
      parameters:
        - name: recipeIds
          required: true
          in: query
          description: レシピID
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: レシピメタデータ取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeMetaDataPresenter'
      tags: *ref_2
      security: *ref_3
  /recipes/bulk:
    post:
      operationId: bulkInsertRecipes
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateRecipeDto'
      responses:
        '201':
          description: レシピ一括登録
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipePresenter'
      tags: *ref_2
      security: *ref_3
  /recipe-books/{id}:
    get:
      operationId: getRecipeBook
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          description: recipeBookId
          schema:
            type: string
      responses:
        '200':
          description: 料理本とユーザー一覧取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeBookPresenter'
      tags: &ref_4
        - recipe-books
      security: &ref_5
        - bearer: []
    put:
      operationId: updateRecipeBook
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRecipeBookDto'
      responses:
        '200':
          description: 料理本更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeBookPresenter'
      tags: *ref_4
      security: *ref_5
  /recipe-books/invitations:
    post:
      operationId: invitationSpace
      summary: ''
      parameters: []
      responses:
        '200':
          description: 料理本の招待
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeBookInvitationPresenter'
      tags: *ref_4
      security: *ref_5
  /recipe-books/joins:
    put:
      operationId: validateInvitation
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateInvitationDto'
      responses:
        '200':
          description: スペース参加の検証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeBookJoinPresenter'
      tags: *ref_4
      security: *ref_5
  /menus:
    get:
      operationId: getMenu
      summary: ''
      parameters: []
      responses:
        '200':
          description: 献立ー一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuPresenter'
      tags: &ref_6
        - menus
      security: &ref_7
        - bearer: []
    post:
      operationId: createMenu
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMenuDto'
      responses:
        '200':
          description: 献立の作成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_6
      security: *ref_7
  /menus/pending:
    get:
      operationId: getPendingMenu
      summary: ''
      parameters: []
      responses:
        '200':
          description: 提案メニュー一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_6
      security: *ref_7
  /menus/{id}:
    put:
      operationId: updateMenu
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMenuDto'
      responses:
        '200':
          description: 献立の更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuPresenter'
      tags: *ref_6
      security: *ref_7
    delete:
      operationId: deleteMenu
      summary: ''
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: 献立の削除
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteMenuPresenter'
      tags: *ref_6
      security: *ref_7
  /auth:
    post:
      operationId: login
      summary: ''
      parameters: []
      responses:
        '201':
          description: ログイン
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresenter'
      tags:
        - auth
      security:
        - bearer: []
info:
  title: reciperu api app
  description: API documents
  version: '1.0'
  contact: {}
tags:
  - name: '1.0'
    description: ''
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    UserPresenter:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        activeStatus:
          type: string
          enum:
            - ONBOARDING
            - JOINED_RECIPE_BOOK
            - NOT_JOINED_RECIPE_BOOK
        recipeBookOwnerId:
          type: string
        recipeBookParticipantId:
          type: string
      required:
        - id
        - name
        - imageUrl
        - activeStatus
    UpdateUserDto:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        activeStatus:
          type: string
          enum:
            - ONBOARDING
            - JOINED_RECIPE_BOOK
            - NOT_JOINED_RECIPE_BOOK
      required:
        - name
        - imageUrl
        - activeStatus
    RecipePresenter:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        recipeBookId:
          type: string
        userId:
          type: string
        isFavorite:
          type: boolean
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
        recipeUrl:
          type: string
        appName:
          type: string
        faviconUrl:
          type: string
        createdAt:
          format: date-time
          type: string
      required:
        - id
        - title
        - recipeBookId
        - userId
        - isFavorite
        - thumbnailUrl
        - imageUrls
        - memo
        - recipeUrl
        - appName
        - faviconUrl
        - createdAt
    PaginatedRecipePresenter:
      type: object
      properties:
        recipes:
          type: array
          items:
            $ref: '#/components/schemas/RecipePresenter'
        nextCursor:
          type: string
      required:
        - recipes
        - nextCursor
    RecipeMetaDataPresenter:
      type: object
      properties:
        title:
          type: string
        thumbnailUrl:
          type: string
        appName:
          type: string
        faviconUrl:
          type: string
      required:
        - title
        - thumbnailUrl
        - appName
        - faviconUrl
    CreateRecipeDto:
      type: object
      properties:
        title:
          type: string
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
        recipeUrl:
          type: string
        faviconUrl:
          type: string
        appName:
          type: string
      required:
        - title
        - thumbnailUrl
        - imageUrls
        - memo
        - recipeUrl
        - faviconUrl
        - appName
    UpdateRecipeDto:
      type: object
      properties:
        title:
          type: string
        isFavorite:
          type: boolean
        thumbnailUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        memo:
          type: string
        recipeUrl:
          type: string
        faviconUrl:
          type: string
        appName:
          type: string
      required:
        - title
        - isFavorite
        - thumbnailUrl
        - imageUrls
        - memo
        - recipeUrl
        - faviconUrl
        - appName
    RecipeBookPresenter:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        users:
          type: array
          items:
            type: string
      required:
        - id
        - name
        - users
    RecipeBookInvitationPresenter:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    ValidateInvitationDto:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    RecipeBookJoinPresenter:
      type: object
      properties:
        success:
          type: boolean
      required:
        - success
    UpdateRecipeBookDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Recipe:
      type: object
      properties: {}
    MenuPresenter:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        scheduledAt:
          format: date-time
          type: string
        userId:
          type: string
        recipeId:
          type: string
        recipe:
          $ref: '#/components/schemas/Recipe'
      required:
        - id
        - status
        - scheduledAt
        - userId
        - recipeId
        - recipe
    CreateMenuDto:
      type: object
      properties:
        recipeId:
          type: string
        scheduledAt:
          format: date-time
          type: string
      required:
        - recipeId
        - scheduledAt
    UpdateMenuDto:
      type: object
      properties:
        status:
          type: string
        scheduledAt:
          format: date-time
          type: string
      required:
        - status
        - scheduledAt
    DeleteMenuPresenter:
      type: object
      properties:
        success:
          type: boolean
      required:
        - success
